{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc9d372b-c333-4247-94ac-27dace5a6039",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torchio as tio\n",
    "from torch.utils.data import DataLoader\n",
    "import os\n",
    "import SimpleITK as sitk\n",
    "from zipfile import ZipFile\n",
    "from zipfile import BadZipFile\n",
    "import dask.dataframe as dd\n",
    "import os\n",
    "import multiprocessing as mp\n",
    "import functools\n",
    "from functools import partial\n",
    "import Standardize\n",
    "import Resampling\n",
    "import utilsPreProcessing\n",
    "from utilsPreProcessing import write_to_modif_path \n",
    "from registration.elastixRegister import reg_adc_hbv_to_t2w\n",
    "\n",
    "df = pd.read_csv('/home/sliceruser/data/metadata/processedMetaData.csv')\n",
    "#currently We want only imagfes with associated masks\n",
    "df = df.loc[df['isAnyMissing'] ==False]\n",
    "df = df.loc[df['isAnythingInAnnotated']>0 ]\n",
    "# ignore all with deficient spacing\n",
    "for keyWord in ['t2w','adc', 'cor','hbv','sag'  ]:    \n",
    "    colName=keyWord+ \"_spac_x\"\n",
    "    df = df.loc[df[colName]>0 ]\n",
    "#just for testing    \n",
    "df=df.sample(n = 4)#TODO remove\n",
    "\n",
    "df.to_csv('/home/sliceruser/data/metadata/processedMetaData_current.csv') \n",
    "\n",
    "########## Standarization\n",
    "\n",
    "import Standardize\n",
    "import pandas as pd\n",
    "trainedModelsBasicPath='/home/sliceruser/data/preprocess/standarizationModels'\n",
    "for keyWord in ['t2w','adc', 'cor','hbv','sag'  ]:\n",
    "    Standardize.iterateAndStandardize(keyWord,df,trainedModelsBasicPath)   \n",
    "Standardize.iterateAndchangeLabelToOnes(df)\n",
    "\n",
    "\n",
    "#######Setting spacing of adc and HBV to t2w so then there would be less resampling needed during registration\n",
    "\n",
    "def resample_adc_hbv_to_t2w(row,secondCol ):\n",
    "    pathT2w= row['t2w']\n",
    "    pathh= row[secondCol] \n",
    "    newPath = pathh.replace(\".mha\",\"_resmaplA.mha\" )\n",
    "    #we check weather resampling was already done if not we do the resampling\n",
    "    if(len(row[secondCol+'_resmaplA'] )<3):\n",
    "        imageT2W = sitk.ReadImage(pathT2w)\n",
    "        targetSpacing = imageT2W.GetSpacing()\n",
    "        try:\n",
    "            resampled = Resampling.resample_with_GAN(pathh,targetSpacing)\n",
    "        except:\n",
    "            print(\"error resampling\")\n",
    "        resampled = Resampling.resample_with_GAN(pathh,targetSpacing)\n",
    "\n",
    "        write_to_modif_path(resampled,pathh,\".mha\",\"_resmaplA.mha\" )\n",
    "    return newPath\n",
    "\n",
    "#needs to be on single thread as resampling GAN is acting on GPU\n",
    "# we save the metadata to main pandas data frame \n",
    "df[\"adc_resmaplA\"]=df.apply(lambda row : resample_adc_hbv_to_t2w(row, 'adc')   , axis = 1) \n",
    "df[\"hbv_resmaplA\"]=df.apply(lambda row : resample_adc_hbv_to_t2w(row, 'hbv')   , axis = 1) \n",
    "df.to_csv('/home/sliceruser/data/metadata/processedMetaData.csv') \n",
    "        \n",
    "\n",
    "#######Registration of adc and hb\n",
    "elacticPath='/home/sliceruser/Slicer/NA-MIC/Extensions-30822/SlicerElastix/lib/Slicer-5.0/elastix'\n",
    "reg_prop='/home/sliceruser/data/piCaiCode/preprocessing/registration/parameters.txt'      \n",
    "        \n",
    "for keyWord in ['adc_resmaplA','hbv_resmaplA']:    \n",
    "    with mp.Pool(processes = mp.cpu_count()) as pool:\n",
    "        pool.map(partial(reg_adc_hbv_to_t2w,colName=keyWord,elacticPath=elacticPath,reg_prop=reg_prop )  ,list(df.iterrows()))    \n",
    " \n",
    "\n",
    "################# get spacing\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
